name: happiday
description: "An elegant app for managing and sending personalized birthday greetings, with reminders, customizable templates, and smart notifications."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  go_router: ^16.0.0
  icons_launcher: ^3.0.1
  shared_preferences: ^2.3.2
  get_it: ^8.0.2
  drift: ^2.28.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.36
  in_app_review: ^2.0.10
  table_calendar: ^3.1.3
  flutter_local_notifications: ^19.3.1
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  gap: ^3.0.1

dev_dependencies:
  drift_dev: ^2.28.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: any
  bloc_test: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
      
